FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel

WORKDIR /app

RUN rm /etc/apt/sources.list.d/cuda-ubuntu2204-x86_64.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --recurse-submodules https://github.com/tdrussell/diffusion-pipe /app

RUN pip install --no-cache-dir -r requirements.txt

CMD NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config /config/hunyuan_video.toml
